const categories = [
  "Beef",
  "Breakfast",
  "Chicken",
  "Dessert",
  "Goat",
  "Lamb",
  "Miscellaneous",
  "Pasta",
  "Pork",
  "Seafood",
  "Side",
  "Starter",
  "Vegan",
  "Vegetarian",
];

const locations = [
  "American",
  "British",
  "Canadian",
  "Chinese",
  "Croatian",
  "Dutch",
  "Egyptian",
  "French",
  "Greek",
  "Indian",
  "Irish",
  "Italian",
  "Jamaican",
  "Japanese",
  "Kenyan",
  "Malaysian",
  "Mexican",
  "Moroccan",
  "Polish",
  "Portuguese",
  "Russian",
  "Spanish",
  "Thai",
  "Tunisian",
  "Turkish",
  "Unknown",
  "Vietnamese",
];

const restaurants = [
  "Baguette Cafe",
  "Cul de Sac Bistro",
  "French Dip Cafe",
  "Samurai Sushi",
  "Crepe Savant",
  " Atomic Sushi",
  "Divine French Dining",
  "Dijonaise Restaurant",
  "Ramen & Rice",
  "Bearnaise",
  "Miso Hungry",
  "Dished Paris",
  "Sushi Junkies",
  "Le Fromage Bistro",
  "Emperor’s Sushi",
  "Escargots Brasserie",
  "French Quarter Cafe",
  "House of Bamboo",
  "Love Sushi",
  "Ahi",
  "Edamame",
];

export { categories, locations, restaurants };
